### ISSUE TITLE
Artist and Gene tests fail locally

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#484]
Definitely has something to do with their artworks grids (the gene one used to fail on the same `variable_size_shows_list_1.default.getFragment` line but now fails earlier on the `refineCallbackPromise`.

```
Summary of all failing tests
 FAIL  build/lib/containers/__tests__/artist-tests.js
  ● Test suite failed to run

    TypeError: variable_size_shows_list_1.default.getFragment is not a function

      at Object.<anonymous> (build/lib/components/artist/shows/index.js:56:36)
      at Object.<anonymous> (build/lib/containers/artist.js:9:13)
      at Object.<anonymous> (build/lib/containers/__tests__/artist-tests.js:6:14)

 FAIL  build/lib/containers/__tests__/gene-tests.js
  ● Test suite failed to run

    /Users/sarahscott/Desktop/dev/emission/build/lib/containers/__tests__/gene-tests.js: babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
    Invalid variable access: refineCallbackPromise
    Whitelisted objects: Array, ArrayBuffer, Boolean, DataView, Date, Error, EvalError, Float32Array, Float64Array, Function, Generator, GeneratorFunction, Infinity, Int16Array, Int32Array, Int8Array, InternalError, Intl, JSON, Map, Math, NaN, Number, Object, Promise, Proxy, RangeError, ReferenceError, Reflect, RegExp, Set, String, Symbol, SyntaxError, TypeError, URIError, Uint16Array, Uint32Array, Uint8Array, Uint8ClampedArray, WeakMap, WeakSet, arguments, expect, jest, require, undefined, DTRACE_NET_SERVER_CONNECTION, DTRACE_NET_STREAM_END, DTRACE_HTTP_SERVER_REQUEST, DTRACE_HTTP_SERVER_RESPONSE, DTRACE_HTTP_CLIENT_REQUEST, DTRACE_HTTP_CLIENT_RESPONSE, global, process, Buffer, clearImmediate, clearInterval, clearTimeout, setImmediate, setInterval, setTimeout, console, __core-js_shared__.
    Note: This is a precaution to guard against uninitialized mock variables. If it is ensured that the mock is required lazily, variable names prefixed with `mock` are permitted.

      at invariant (node_modules/babel-plugin-jest-hoist/build/index.js:13:11)
      at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
      at TraversalContext.visitMultiple (node_modules/babel-traverse/lib/context.js:103:17)
      at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:190:19)
```

**Comment by orta** [comment]
Were these skipped, the build is now green?

**Comment by sarahscott** [comment]
Right, these are fine in CI but still fail for me locally.

**Comment by orta** [comment]
Weird, have you tried `rm -rf node_modules`? What's your node version? a normal `yarn jest` runs fine for me

**Comment by sarahscott** [comment]
Yeah I've tried removing and re-installing the modules. Node version is v6.10.1. I can look into a bit more and if it's only happening on my machine, we can close this issue.

**Comment by orta** [comment]
If it could happen to you, it could happen to anyone, it's worth understanding

This is the CI setup:
![screen shot 2017-05-22 at 18 40 23](https://cloud.githubusercontent.com/assets/49038/26321304/30872a78-3f1e-11e7-9f6e-e0912045ab5f.png)

**Comment by sarahscott** [comment]
Hmm... here's mine:
<img width="309" alt="screen shot 2017-05-22 at 19 47 46" src="https://cloud.githubusercontent.com/assets/2712962/26321572/91efddb0-3f27-11e7-9797-72ae3e23c103.png">

**Comment by sarahscott** [comment]
Can be fixed by running `yarn test -- --no-cache`
